---

- name: Rolling out common configuration on all hosts
  hosts: all
  become: true
  gather_facts: yes
  
  roles:
   - common

- name: Installing Elasticsearch server instance
  hosts: elasticsearch-server
  gather_facts: yes
  become: true

  roles:
   - elasticsearch
   
- name: Installing kibana
  hosts: kibana-server
  gather_facts: yes
  become: true
  
  roles:
   - kibana
